### ISSUE TITLE
Play a sound on connection/disconnection?

### ISSUE THREAD

**Issue by hadess** [adenbeckitt/Bluez-AVRCP-Volume-Control#4]
Are you interested in having this:
https://github.com/hadess/CHIP-bluetooth-speaker/issues/22
in your script?

If so, I can look at implementing it. I have this functionality in a UE-Roll Bluetooth speaker, and it's super useful when you don't have a screen to see if the connection worked, or when the phone/laptop disconnected.

**Comment by hadess** [comment]
I've added this to my own script[1], ported to GDBus. Thanks for the example code, much appreciated.

[1]: https://github.com/hadess/CHIP-bluetooth-speaker/blob/master/bluetooth-volume-handler.py

**Comment by patriot1889** [comment]
Apologies for not replying. I've been very busy recently. I meant to reply, I just forgot. Shame on me. 

Glad you got it sorted. I've basically rewritten this whole project and it does indeed include connection and disconnection sounds amongst other goodies. 

I'll probably put it up here when it's finished.

**Comment by hadess** [comment]
Happy to retire my attempt at this if your version is more mature and tested than mine.

I'll probably take a look when I've received some hardware that I'm missing, and will look to put the thing back in production, but don't hesitate to post in the bug I referenced above if you make headway.
